### ISSUE TITLE
new address existing group: blackbasta

### ISSUE THREAD

**Issue by joshhighet** [thetanz/ransomwatch#14]
### host location

http://aazsbsgya565vlu2c6bzy6yfiebkcbtvvcytvolt33s77xypi7nypxyd.onion/

### group name

blackbasta

### group information

https://t.me/arvin_club/5387

### host

v3 (onion)

### parser

```shell
unknown, appears down, ret. code 400
```

**Comment by soufianetahiri** [comment]
Thanks don't hesitate to make a PR
