### ISSUE TITLE
new group: RA Group 

### ISSUE THREAD

**Issue by milxss** [thetanz/ransomwatch#60]
### host location

http://pa32ymaeu62yo5th5mraikgw5fcvznnsiiwti42carjliarodltmqcqd.onion

### group name

RA Group

### group information

Hey, 
I checked beforehand and it seems not to be covered yet by the Ransomwatch. That's a new cyber threat actor called RA group and they already count several victims, hope it will be useful. Thank you for your service!

### host

v3 (onion)

**Comment by joshhighet** [comment]
hi! thanks for the contribution. ragroup has already been added, you can view it here https://ransomwatch.telemetry.ltd/#/profiles?id=ragroup. i will close this for now

**Comment by milxss** [comment]
crazy fast! I've been literally searching by the victims and the .onion address itself, got no related results. Thank you and sorry for bothering 🤯
